// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: idl/tags.proto

package tags_service

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid  uint64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Tags string `protobuf:"bytes,2,opt,name=tags,proto3" json:"tags,omitempty"`
}

func (x *CreateTagsRequest) Reset() {
	*x = CreateTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_tags_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagsRequest) ProtoMessage() {}

func (x *CreateTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_tags_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagsRequest.ProtoReflect.Descriptor instead.
func (*CreateTagsRequest) Descriptor() ([]byte, []int) {
	return file_idl_tags_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTagsRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CreateTagsRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type CreateTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateTagsResponse) Reset() {
	*x = CreateTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_tags_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagsResponse) ProtoMessage() {}

func (x *CreateTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_tags_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagsResponse.ProtoReflect.Descriptor instead.
func (*CreateTagsResponse) Descriptor() ([]byte, []int) {
	return file_idl_tags_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagsResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateTagsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DelTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid  uint64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Tags string `protobuf:"bytes,2,opt,name=tags,proto3" json:"tags,omitempty"`
}

func (x *DelTagsRequest) Reset() {
	*x = DelTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_tags_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTagsRequest) ProtoMessage() {}

func (x *DelTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_tags_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTagsRequest.ProtoReflect.Descriptor instead.
func (*DelTagsRequest) Descriptor() ([]byte, []int) {
	return file_idl_tags_proto_rawDescGZIP(), []int{2}
}

func (x *DelTagsRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DelTagsRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type DelTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DelTagsResponse) Reset() {
	*x = DelTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_tags_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTagsResponse) ProtoMessage() {}

func (x *DelTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_tags_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTagsResponse.ProtoReflect.Descriptor instead.
func (*DelTagsResponse) Descriptor() ([]byte, []int) {
	return file_idl_tags_proto_rawDescGZIP(), []int{3}
}

func (x *DelTagsResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DelTagsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_idl_tags_proto protoreflect.FileDescriptor

var file_idl_tags_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x64, 0x6c, 0x2f, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x39, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x22, 0x3e, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x36, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x3b, 0x0a, 0x0f, 0x44, 0x65, 0x6c,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x86, 0x01, 0x0a, 0x0b, 0x54, 0x61, 0x67, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x67, 0x73, 0x12, 0x17, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x74, 0x61, 0x67, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x54, 0x61,
	0x67, 0x73, 0x12, 0x14, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e,
	0x44, 0x65, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x54,
	0x75, 0x2d, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x57, 0x65, 0x47, 0x6f, 0x2f, 0x69, 0x74, 0x75, 0x5f,
	0x72, 0x70, 0x63, 0x5f, 0x74, 0x61, 0x67, 0x73, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67,
	0x65, 0x6e, 0x2f, 0x74, 0x61, 0x67, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_tags_proto_rawDescOnce sync.Once
	file_idl_tags_proto_rawDescData = file_idl_tags_proto_rawDesc
)

func file_idl_tags_proto_rawDescGZIP() []byte {
	file_idl_tags_proto_rawDescOnce.Do(func() {
		file_idl_tags_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_tags_proto_rawDescData)
	})
	return file_idl_tags_proto_rawDescData
}

var file_idl_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_tags_proto_goTypes = []interface{}{
	(*CreateTagsRequest)(nil),  // 0: tags.CreateTagsRequest
	(*CreateTagsResponse)(nil), // 1: tags.CreateTagsResponse
	(*DelTagsRequest)(nil),     // 2: tags.DelTagsRequest
	(*DelTagsResponse)(nil),    // 3: tags.DelTagsResponse
}
var file_idl_tags_proto_depIdxs = []int32{
	0, // 0: tags.TagsService.CreateTags:input_type -> tags.CreateTagsRequest
	2, // 1: tags.TagsService.DelTags:input_type -> tags.DelTagsRequest
	1, // 2: tags.TagsService.CreateTags:output_type -> tags.CreateTagsResponse
	3, // 3: tags.TagsService.DelTags:output_type -> tags.DelTagsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_tags_proto_init() }
func file_idl_tags_proto_init() {
	if File_idl_tags_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_tags_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_tags_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_tags_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_tags_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_tags_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_tags_proto_goTypes,
		DependencyIndexes: file_idl_tags_proto_depIdxs,
		MessageInfos:      file_idl_tags_proto_msgTypes,
	}.Build()
	File_idl_tags_proto = out.File
	file_idl_tags_proto_rawDesc = nil
	file_idl_tags_proto_goTypes = nil
	file_idl_tags_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.12.3. DO NOT EDIT.

type TagsService interface {
	CreateTags(ctx context.Context, req *CreateTagsRequest) (res *CreateTagsResponse, err error)
	DelTags(ctx context.Context, req *DelTagsRequest) (res *DelTagsResponse, err error)
}
