Kitex:
  Service: "tag_service"
  Address: "0.0.0.0:8888"
  LogLevel: info
  LogFileName: "log/kitex.log"
  LogMaxSize: 10
  LogMaxAge: 3
  LogMaxBackups: 50

Registry:
  RegistryAddress:
  - 127.0.0.1:2379
  Username: ""
  Password: ""

PostgresSQL:
  Host: 127.0.0.1
  User: postgres
  Password: 123456
  Dbname: ITU
  Port: 5432
  SSLMode: disable

