// Code generated by Kitex v0.12.3. DO NOT EDIT.

package tagsservice

import (
	"context"
	"errors"
	tags_service "github.com/ITu-CloudWeGo/itu_rpc_tags/kitex_gen/tags_service"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PidTidCreate": kitex.NewMethodInfo(
		pidTidCreateHandler,
		newPidTidCreateArgs,
		newPidTidCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetTags": kitex.NewMethodInfo(
		getTagsHandler,
		newGetTagsArgs,
		newGetTagsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetTagID": kitex.NewMethodInfo(
		getTagIDHandler,
		newGetTagIDArgs,
		newGetTagIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	tagsServiceServiceInfo                = NewServiceInfo()
	tagsServiceServiceInfoForClient       = NewServiceInfoForClient()
	tagsServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return tagsServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return tagsServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return tagsServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TagsService"
	handlerType := (*tags_service.TagsService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "tags",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func pidTidCreateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tags_service.PidTidCreateRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tags_service.TagsService).PidTidCreate(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PidTidCreateArgs:
		success, err := handler.(tags_service.TagsService).PidTidCreate(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PidTidCreateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPidTidCreateArgs() interface{} {
	return &PidTidCreateArgs{}
}

func newPidTidCreateResult() interface{} {
	return &PidTidCreateResult{}
}

type PidTidCreateArgs struct {
	Req *tags_service.PidTidCreateRequest
}

func (p *PidTidCreateArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(tags_service.PidTidCreateRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *PidTidCreateArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *PidTidCreateArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *PidTidCreateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PidTidCreateArgs) Unmarshal(in []byte) error {
	msg := new(tags_service.PidTidCreateRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PidTidCreateArgs_Req_DEFAULT *tags_service.PidTidCreateRequest

func (p *PidTidCreateArgs) GetReq() *tags_service.PidTidCreateRequest {
	if !p.IsSetReq() {
		return PidTidCreateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PidTidCreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PidTidCreateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PidTidCreateResult struct {
	Success *tags_service.PidTidCreateResponse
}

var PidTidCreateResult_Success_DEFAULT *tags_service.PidTidCreateResponse

func (p *PidTidCreateResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(tags_service.PidTidCreateResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *PidTidCreateResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *PidTidCreateResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *PidTidCreateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PidTidCreateResult) Unmarshal(in []byte) error {
	msg := new(tags_service.PidTidCreateResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PidTidCreateResult) GetSuccess() *tags_service.PidTidCreateResponse {
	if !p.IsSetSuccess() {
		return PidTidCreateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PidTidCreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*tags_service.PidTidCreateResponse)
}

func (p *PidTidCreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PidTidCreateResult) GetResult() interface{} {
	return p.Success
}

func getTagsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tags_service.GetTagsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tags_service.TagsService).GetTags(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetTagsArgs:
		success, err := handler.(tags_service.TagsService).GetTags(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetTagsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetTagsArgs() interface{} {
	return &GetTagsArgs{}
}

func newGetTagsResult() interface{} {
	return &GetTagsResult{}
}

type GetTagsArgs struct {
	Req *tags_service.GetTagsRequest
}

func (p *GetTagsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(tags_service.GetTagsRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetTagsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetTagsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetTagsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetTagsArgs) Unmarshal(in []byte) error {
	msg := new(tags_service.GetTagsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetTagsArgs_Req_DEFAULT *tags_service.GetTagsRequest

func (p *GetTagsArgs) GetReq() *tags_service.GetTagsRequest {
	if !p.IsSetReq() {
		return GetTagsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetTagsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetTagsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetTagsResult struct {
	Success *tags_service.GetTagsResponse
}

var GetTagsResult_Success_DEFAULT *tags_service.GetTagsResponse

func (p *GetTagsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(tags_service.GetTagsResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetTagsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetTagsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetTagsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetTagsResult) Unmarshal(in []byte) error {
	msg := new(tags_service.GetTagsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetTagsResult) GetSuccess() *tags_service.GetTagsResponse {
	if !p.IsSetSuccess() {
		return GetTagsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetTagsResult) SetSuccess(x interface{}) {
	p.Success = x.(*tags_service.GetTagsResponse)
}

func (p *GetTagsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetTagsResult) GetResult() interface{} {
	return p.Success
}

func getTagIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tags_service.GetTagIDRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tags_service.TagsService).GetTagID(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetTagIDArgs:
		success, err := handler.(tags_service.TagsService).GetTagID(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetTagIDResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetTagIDArgs() interface{} {
	return &GetTagIDArgs{}
}

func newGetTagIDResult() interface{} {
	return &GetTagIDResult{}
}

type GetTagIDArgs struct {
	Req *tags_service.GetTagIDRequest
}

func (p *GetTagIDArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(tags_service.GetTagIDRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetTagIDArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetTagIDArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetTagIDArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetTagIDArgs) Unmarshal(in []byte) error {
	msg := new(tags_service.GetTagIDRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetTagIDArgs_Req_DEFAULT *tags_service.GetTagIDRequest

func (p *GetTagIDArgs) GetReq() *tags_service.GetTagIDRequest {
	if !p.IsSetReq() {
		return GetTagIDArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetTagIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetTagIDArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetTagIDResult struct {
	Success *tags_service.GetTagIDResponse
}

var GetTagIDResult_Success_DEFAULT *tags_service.GetTagIDResponse

func (p *GetTagIDResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(tags_service.GetTagIDResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetTagIDResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetTagIDResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetTagIDResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetTagIDResult) Unmarshal(in []byte) error {
	msg := new(tags_service.GetTagIDResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetTagIDResult) GetSuccess() *tags_service.GetTagIDResponse {
	if !p.IsSetSuccess() {
		return GetTagIDResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetTagIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*tags_service.GetTagIDResponse)
}

func (p *GetTagIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetTagIDResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PidTidCreate(ctx context.Context, Req *tags_service.PidTidCreateRequest) (r *tags_service.PidTidCreateResponse, err error) {
	var _args PidTidCreateArgs
	_args.Req = Req
	var _result PidTidCreateResult
	if err = p.c.Call(ctx, "PidTidCreate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTags(ctx context.Context, Req *tags_service.GetTagsRequest) (r *tags_service.GetTagsResponse, err error) {
	var _args GetTagsArgs
	_args.Req = Req
	var _result GetTagsResult
	if err = p.c.Call(ctx, "GetTags", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTagID(ctx context.Context, Req *tags_service.GetTagIDRequest) (r *tags_service.GetTagIDResponse, err error) {
	var _args GetTagIDArgs
	_args.Req = Req
	var _result GetTagIDResult
	if err = p.c.Call(ctx, "GetTagID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
